name = "poi-web-kai"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat_v2"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

routes = [
  { pattern = "poi.moe", custom_domain = true },
  { pattern = "www.poi.moe", custom_domain = true },
]
