name = "poi-web-kai"
compatibility_date = "2026-06-21"
compatibility_flags = ["nodejs_compat"]
main = "src/worker.ts"

routes = [
  { pattern = "poi.moe", custom_domain = true },
  { pattern = "update.poi.moe", custom_domain = true },
]

[assets]
directory = "dist/client"
binding = "ASSETS"

[observability]
enabled = true
