import '~/styles/globals.css'

import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'

import { Background } from '~/components/background'
import { Header } from '~/components/header'
import { I18nProvider } from '~/components/i18n-provider'
import { ThemeProvider } from '~/components/theme-provider'
import { initTranslations } from '~/i18n'
import { i18nConfig } from '~/i18n-config'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export const generateStaticParams = async () => {
  return i18nConfig.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: {
    locale: string
  }
}>) {
  const { resources } = await initTranslations(locale, ['common'])
  return (
    <html
      lang={locale}
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Background />
          <I18nProvider
            locale={locale}
            namespaces={['common']}
            resources={resources}
          >
            <main className="relative z-0 flex min-h-screen flex-col items-center justify-center">
              <Header />
              {children}
            </main>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
