/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as OpengraphImageRouteImport } from './routes/opengraph-image'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TwitterImageRouteImport } from './routes/twitter-image'
import { Route as ApiMonitoringRouteImport } from './routes/api.monitoring'
import { Route as ChangelogCompareRouteImport } from './routes/changelog_.compare'
import { Route as DistFilenameRouteImport } from './routes/dist.$filename'
import { Route as FcdFilenameRouteImport } from './routes/fcd.$filename'
import { Route as UpdateFilenameRouteImport } from './routes/update.$filename'
import { Route as ApiChangelogChannelRouteImport } from './routes/api.changelog.$channel'
import { Route as ApiCreditsSpriteFilenameRouteImport } from './routes/api.credits-sprite.$filename'
import { Route as ApiCreditsFilenameRouteImport } from './routes/api.credits.$filename'
import { Route as ApiCreditsManifestDotjsonRouteImport } from './routes/api.credits.manifest[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphImageRoute = OpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitterImageRoute = TwitterImageRouteImport.update({
  id: '/twitter-image',
  path: '/twitter-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringRoute = ApiMonitoringRouteImport.update({
  id: '/api/monitoring',
  path: '/api/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogCompareRoute = ChangelogCompareRouteImport.update({
  id: '/changelog_/compare',
  path: '/changelog/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DistFilenameRoute = DistFilenameRouteImport.update({
  id: '/dist/$filename',
  path: '/dist/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const FcdFilenameRoute = FcdFilenameRouteImport.update({
  id: '/fcd/$filename',
  path: '/fcd/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateFilenameRoute = UpdateFilenameRouteImport.update({
  id: '/update/$filename',
  path: '/update/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogChannelRoute = ApiChangelogChannelRouteImport.update({
  id: '/api/changelog/$channel',
  path: '/api/changelog/$channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsSpriteFilenameRoute =
  ApiCreditsSpriteFilenameRouteImport.update({
    id: '/api/credits-sprite/$filename',
    path: '/api/credits-sprite/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCreditsFilenameRoute = ApiCreditsFilenameRouteImport.update({
  id: '/api/credits/$filename',
  path: '/api/credits/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsManifestDotjsonRoute =
  ApiCreditsManifestDotjsonRouteImport.update({
    id: '/api/credits/manifest.json',
    path: '/api/credits/manifest.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/credits': typeof CreditsRoute
  '/download': typeof DownloadRoute
  '/explore': typeof ExploreRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/plugins': typeof PluginsRoute
  '/status': typeof StatusRoute
  '/twitter-image': typeof TwitterImageRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/changelog/compare': typeof ChangelogCompareRoute
  '/dist/$filename': typeof DistFilenameRoute
  '/fcd/$filename': typeof FcdFilenameRoute
  '/update/$filename': typeof UpdateFilenameRoute
  '/api/changelog/$channel': typeof ApiChangelogChannelRoute
  '/api/credits-sprite/$filename': typeof ApiCreditsSpriteFilenameRoute
  '/api/credits/$filename': typeof ApiCreditsFilenameRoute
  '/api/credits/manifest.json': typeof ApiCreditsManifestDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/credits': typeof CreditsRoute
  '/download': typeof DownloadRoute
  '/explore': typeof ExploreRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/plugins': typeof PluginsRoute
  '/status': typeof StatusRoute
  '/twitter-image': typeof TwitterImageRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/changelog/compare': typeof ChangelogCompareRoute
  '/dist/$filename': typeof DistFilenameRoute
  '/fcd/$filename': typeof FcdFilenameRoute
  '/update/$filename': typeof UpdateFilenameRoute
  '/api/changelog/$channel': typeof ApiChangelogChannelRoute
  '/api/credits-sprite/$filename': typeof ApiCreditsSpriteFilenameRoute
  '/api/credits/$filename': typeof ApiCreditsFilenameRoute
  '/api/credits/manifest.json': typeof ApiCreditsManifestDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/credits': typeof CreditsRoute
  '/download': typeof DownloadRoute
  '/explore': typeof ExploreRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/plugins': typeof PluginsRoute
  '/status': typeof StatusRoute
  '/twitter-image': typeof TwitterImageRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/changelog_/compare': typeof ChangelogCompareRoute
  '/dist/$filename': typeof DistFilenameRoute
  '/fcd/$filename': typeof FcdFilenameRoute
  '/update/$filename': typeof UpdateFilenameRoute
  '/api/changelog/$channel': typeof ApiChangelogChannelRoute
  '/api/credits-sprite/$filename': typeof ApiCreditsSpriteFilenameRoute
  '/api/credits/$filename': typeof ApiCreditsFilenameRoute
  '/api/credits/manifest.json': typeof ApiCreditsManifestDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/credits'
    | '/download'
    | '/explore'
    | '/opengraph-image'
    | '/plugins'
    | '/status'
    | '/twitter-image'
    | '/api/monitoring'
    | '/changelog/compare'
    | '/dist/$filename'
    | '/fcd/$filename'
    | '/update/$filename'
    | '/api/changelog/$channel'
    | '/api/credits-sprite/$filename'
    | '/api/credits/$filename'
    | '/api/credits/manifest.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/credits'
    | '/download'
    | '/explore'
    | '/opengraph-image'
    | '/plugins'
    | '/status'
    | '/twitter-image'
    | '/api/monitoring'
    | '/changelog/compare'
    | '/dist/$filename'
    | '/fcd/$filename'
    | '/update/$filename'
    | '/api/changelog/$channel'
    | '/api/credits-sprite/$filename'
    | '/api/credits/$filename'
    | '/api/credits/manifest.json'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/credits'
    | '/download'
    | '/explore'
    | '/opengraph-image'
    | '/plugins'
    | '/status'
    | '/twitter-image'
    | '/api/monitoring'
    | '/changelog_/compare'
    | '/dist/$filename'
    | '/fcd/$filename'
    | '/update/$filename'
    | '/api/changelog/$channel'
    | '/api/credits-sprite/$filename'
    | '/api/credits/$filename'
    | '/api/credits/manifest.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  CreditsRoute: typeof CreditsRoute
  DownloadRoute: typeof DownloadRoute
  ExploreRoute: typeof ExploreRoute
  OpengraphImageRoute: typeof OpengraphImageRoute
  PluginsRoute: typeof PluginsRoute
  StatusRoute: typeof StatusRoute
  TwitterImageRoute: typeof TwitterImageRoute
  ApiMonitoringRoute: typeof ApiMonitoringRoute
  ChangelogCompareRoute: typeof ChangelogCompareRoute
  DistFilenameRoute: typeof DistFilenameRoute
  FcdFilenameRoute: typeof FcdFilenameRoute
  UpdateFilenameRoute: typeof UpdateFilenameRoute
  ApiChangelogChannelRoute: typeof ApiChangelogChannelRoute
  ApiCreditsSpriteFilenameRoute: typeof ApiCreditsSpriteFilenameRoute
  ApiCreditsFilenameRoute: typeof ApiCreditsFilenameRoute
  ApiCreditsManifestDotjsonRoute: typeof ApiCreditsManifestDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph-image': {
      id: '/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/opengraph-image'
      preLoaderRoute: typeof OpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitter-image': {
      id: '/twitter-image'
      path: '/twitter-image'
      fullPath: '/twitter-image'
      preLoaderRoute: typeof TwitterImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring': {
      id: '/api/monitoring'
      path: '/api/monitoring'
      fullPath: '/api/monitoring'
      preLoaderRoute: typeof ApiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog_/compare': {
      id: '/changelog_/compare'
      path: '/changelog/compare'
      fullPath: '/changelog/compare'
      preLoaderRoute: typeof ChangelogCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dist/$filename': {
      id: '/dist/$filename'
      path: '/dist/$filename'
      fullPath: '/dist/$filename'
      preLoaderRoute: typeof DistFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fcd/$filename': {
      id: '/fcd/$filename'
      path: '/fcd/$filename'
      fullPath: '/fcd/$filename'
      preLoaderRoute: typeof FcdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update/$filename': {
      id: '/update/$filename'
      path: '/update/$filename'
      fullPath: '/update/$filename'
      preLoaderRoute: typeof UpdateFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog/$channel': {
      id: '/api/changelog/$channel'
      path: '/api/changelog/$channel'
      fullPath: '/api/changelog/$channel'
      preLoaderRoute: typeof ApiChangelogChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits-sprite/$filename': {
      id: '/api/credits-sprite/$filename'
      path: '/api/credits-sprite/$filename'
      fullPath: '/api/credits-sprite/$filename'
      preLoaderRoute: typeof ApiCreditsSpriteFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/$filename': {
      id: '/api/credits/$filename'
      path: '/api/credits/$filename'
      fullPath: '/api/credits/$filename'
      preLoaderRoute: typeof ApiCreditsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/manifest.json': {
      id: '/api/credits/manifest.json'
      path: '/api/credits/manifest.json'
      fullPath: '/api/credits/manifest.json'
      preLoaderRoute: typeof ApiCreditsManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  CreditsRoute: CreditsRoute,
  DownloadRoute: DownloadRoute,
  ExploreRoute: ExploreRoute,
  OpengraphImageRoute: OpengraphImageRoute,
  PluginsRoute: PluginsRoute,
  StatusRoute: StatusRoute,
  TwitterImageRoute: TwitterImageRoute,
  ApiMonitoringRoute: ApiMonitoringRoute,
  ChangelogCompareRoute: ChangelogCompareRoute,
  DistFilenameRoute: DistFilenameRoute,
  FcdFilenameRoute: FcdFilenameRoute,
  UpdateFilenameRoute: UpdateFilenameRoute,
  ApiChangelogChannelRoute: ApiChangelogChannelRoute,
  ApiCreditsSpriteFilenameRoute: ApiCreditsSpriteFilenameRoute,
  ApiCreditsFilenameRoute: ApiCreditsFilenameRoute,
  ApiCreditsManifestDotjsonRoute: ApiCreditsManifestDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
